openapi: 3.0.3
info:
  title: GP SERAM
  version: 2.0.0
  description: >-
    This specification allows a Remote Admin Agent to manage a Secure Element
    thanks to a Local Admin Agent.  <br> <br> 2 layers is provided here:<br> -
    the data model which details messages which are exchanges. Refer to the
    Schemas section below.<br> - the HTTP REST binding, details in terms of
    HTTP GET and POST methods. Refer to initialization and
    seApplicationManagement phase below.<br> <br> The Remote Admin Agent is
    acting as an HTTP server and the Local Admin Agent as an HTTP Client.
    During the initialization phase, the local Admin Agent provides a list of
    supported data format and transport protocol. The server selects the best
    option and  continue with the selected binding.  This OpenAPI specification
    is self-documentated. Please refer to the [ GP SERAM
    github](http://github.com/slegouix/SERAM) for additional information.
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: seApplicationManagementService
    description: >-
      Remote Admin Agent performs the remote management by sending orders to
      the Local Admin Agent
servers:
  - url: '{protocol}://{domain}/gp/seram'
    variables:
      domain:
        default: localhost
        description: server domain
      protocol:
        enum:
          - http
          - https
        default: https
paths:
  /handshake:
    post:
      tags:
        - seApplicationManagementService
      summary: method used to negociate data format and the transport protocol
      description: >-
        This method shall be used by the HTTP client to tell which data formats
        and which transport protocols it supports. In response, the HTTP server
        shall tell which ones it selects.<br> <br> The DataFormat describes
        which data format is used for message payloads.<br> <br> The
        TransportProtocol describes the transport protocol binding. It details
        how setting-up the transport layer (if required), exchanging the
        messages payload between RAA and LAA, keeping the integrity of the
        remote management session and resuming communications in case of a data
        exchange failure<br> <br> The HTTP client shall used the sessionId to
        allow the HTTP server to track the remote management. The HTTP client
        shall reused the sessionId in all subsequent HTTP request to the HTTP
        server
      parameters:
        - name: sessionId
          in: query
          required: true
          schema:
            description: >-
              An identifier shared between the Device Application and the
              Management Platform and associated with a Management Session.
            type: string
            example: 0f96af97-f879-45a2-a011-ee7439df3804
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: >-
                This is the data model for the handshake command. <br><br> If
                supportedTransportProtocol is not provided, HTTPS is assumed.
                If supportedDataFormat is not provided, application/json is
                assumed. <br>If supportedVersions is not provided, 2.0.0 is
                assumed. secureElements shall be ordered by preference by the
                client. 
              type: object
              required:
                - secureElements
              properties:
                secureElements:
                  description: A list of Secure Element available on Local Agent side.
                  type: array
                  items:
                    $ref: >-
                      #/components/schemas/remoteManagementOrder/properties/chosenSecureElement/allOf/1
                supportedTransportProtocols:
                  description: >-
                    A list of Transport Protocol supported by the the Local
                    Agent.
                  type: array
                  items:
                    description: A transport protocol to exchange GPSERAM Messages.
                    type: string
                    enum:
                      - HTTPS
                      - CoAP
                supportedDataFormats:
                  description: >-
                    A list of Transport Data Format supported by the Local
                    Agent.
                  type: array
                  items:
                    description: Encoding format of GP SERAM Messages
                    type: string
                    enum:
                      - application/json
                      - application/cbor
                supportedVersions:
                  description: A list of version of GP SERAM supported by the Local Agent.
                  type: array
                  items:
                    description: A Version of GP SERAM
                    type: string
                    example: 2.0.0
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: >-
                  The Handshake Response Message is the Message used by the
                  Remote Agent during the Handshake step. Each value of the
                  chosen properties shall correspond of one supported by the
                  Local Agent.
                required:
                  - chosenDataProtocol
                  - chosenTransportProtocol
                  - chosenVersion
                properties:
                  chosenTransportProtocol:
                    allOf:
                      - description: The Transport Protocol selected by the Remote Agent.
                      - $ref: >-
                          #/paths/~1handshake/post/requestBody/content/application~1json/schema/properties/supportedTransportProtocols/items
                  chosenDataFormat:
                    allOf:
                      - description: The Data Protocol selected by the Remote Agent.
                      - $ref: >-
                          #/paths/~1handshake/post/requestBody/content/application~1json/schema/properties/supportedDataFormats/items
                  chosenVersion:
                    allOf:
                      - description: The Version of GP SERAM selected by the Remote Agent
                      - $ref: >-
                          #/paths/~1handshake/post/requestBody/content/application~1json/schema/properties/supportedVersions/items
        '404':
          description: Session id not found
        '406':
          description: HTTP Server could not fulfill the client proposal
        '500':
          description: Unknown server error
  /remoteManagement:
    post:
      tags:
        - seApplicationManagementService
      summary: Method used to respond to a remote management command.
      description: >-
        This method shall be used by the HTTP client to transmit its response
        to the HTTP server. <br><br> In response, the HTTP server shall send
        the next remote management order.
      parameters:
        - name: sessionId
          in: query
          required: true
          schema:
            $ref: '#/paths/~1handshake/post/parameters/0/schema'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/remoteManagementMsg'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/remoteManagementOrder'
        '404':
          description: Session id not found
        '500':
          description: Unknown server error
components:
  schemas:
    remoteManagementOrder:
      description: >-
        This is the data model for the remote management order. The Remote
        Agent may used it to maintain the connection with the Local Agent or to
        send Message Command to the Local Agent. All fields are optional.
      properties:
        delay:
          description: >-
            Delay in second the device local agent had to wait before sending
            data to the platform.
          type: integer
          default: 1
        chosenSecureElement:
          allOf:
            - description: >-
                Set the Secure Element the Local Agent SHALL used to send
                C-APDU
            - description: >-
                A Secure Element. It is composed of the type of Secure Element
                and the identifier of the Secure Element. Moreover, it may
                includes an additional field to provide some additional
                informations related to the Secure Element (E.g. the support
                the GP SAM)
              type: object
              required:
                - seType
                - seId
              properties:
                seType:
                  description: Type of Secure Element.
                  type: string
                  enum:
                    - eSE
                    - iSE
                    - uicc
                    - euicc
                    - ieuicc
                seId:
                  description: Identifier of the Secure Element.
                  type: string
                  example: '89001012012341234012345678901224'
                seExtraInfo:
                  description: A comma separated list of features supported by the SE.
                  type: string
                  example: SAM
        ramCommands:
          description: List of Commands to be executed by the Local Agent.
          type: array
          items:
            description: >-
              Command Messages are sent by the Remote Agent and shall be
              executed by the Local Agent.
            required:
              - ramCommandType
            discriminator:
              propertyName: ramCommandType
              mapping:
                ramStartCommand: attributes.yaml#/ramStartCommand
                seRamCommand: attributes.yaml#/seRamCommand
                notificationCommand: attributes.yaml#/notificationCommand
                ramStopCommand: attributes.yaml#/ramStopCommand
            properties:
              ramCommandType:
                description: >-
                  The type of Command Message with authorized values listed in
                  the discrimitator mapping
                type: string
    remoteManagementMsg:
      description: >-
        This is the data model for the remote management containing SE ram
        responses. In case of polling message, or for the first polling
        message, only the localAgentStatus is included.
      type: object
      required:
        - localAgentStatus
      properties:
        localAgentStatus:
          allOf:
            - description: Status of the Local Agent
            - description: >-
                The Local Agent SHALL sent a status in each request to the HTTP
                server.
              required:
                - localAgentStatusEnum
                - executedRamCommands
              properties:
                localAgentStatusEnum:
                  description: >-
                    Local Agent SHALL send a PROCESSED status whenever at least
                    one RAM command has been executed. On any error processing
                    one of UNAVAILABLE_SE, UNKNOWN_FAILURE, or UNGRANTED_ACCESS
                    SHALL used. And the POLLING status SHALL be used for the
                    first HTTP request or is the Remote Agent hasn't sent any
                    Command.
                  enum:
                    - PROCESSED
                    - POLLING
                    - UNAVAILABLE_SE
                    - UNKNOWN_FAILURE
                    - UNGRANTED_ACCESS
                executedRamCommands:
                  description: >-
                    Number of RAM command executed. Value SHALL be set to zero
                    during polling
                  type: integer
                errorMsg:
                  description: >-
                    Additional information provided in case of error (status
                    UNAVAILABLE_SE, UNKNOWN_FAILURE, UNGRANDED_ACCESS) that
                    should be logged for investigation or for legal purpose.
                  type: string
        ramResponses:
          description: The list of RAM responses
          type: array
          items:
            description: Response Messages are sent by the Local Agent to the Agent.
            required:
              - ramResponseType
            discriminator:
              propertyName: ramResponseType
              mapping:
                seRamResponse: attributes.yaml#/seRamResponse
            properties:
              ramResponseType:
                description: >-
                  The type of Response Message with authorized values listed in
                  the discrimitator mapping
                type: string
